name: CI workflows
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - name: Install PNPM
              uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
              with:
                  version: 6.32.7

            - name: Set up Node v16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install -r

            - name: Run linter
              run: pnpm run lint

    typescript:
        name: TypeScript Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

            - name: Install PNPM
              uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
              with:
                  version: 6.32.7

            - name: Install Node v14
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install -r

            - name: Run TypeScript Compiler
              run: pnpm run build

    tests:
        name: Mocha tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

            - name: Install PNPM
              uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
              with:
                  version: 6.32.7

            - name: Install Node v14
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install -r

            - name: Run TypeScript Compiler
              run: pnpm run build

            - name: Run tests
              run: pnpm run test
