name: Deploy Docs
on:
    push:
        branches:
            - main
jobs:
    docs:
        name: Deploy Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install PNPM
              uses: pnpm/action-setup@57b9359b4c69c79ca51422d02ca739a7957f4aed
              with:
                  version: 6.32.7

            - name: Install Node v14
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install -r

            - name: Build project
              run: pnpm run build

            - name: Build the docs
              run: pnpm run docs

            - name: Commit the Docs
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "docs"
                  destination-github-username: "github-actions[bot]"
                  destination-repository-username: "guildedjs"
                  destination-repository-name: "guildedjs.github.io"
                  target-branch: "main"
                  user-email: 41898282+github-actions[bot]@users.noreply.github.com
